name: Deploy to Server via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Copiar archivos al servidor mediante SFTP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 2222 # Puerto común de Neubox. Si no conecta, cámbialo a 22.
        source: "./*"
        target: "/home/cncmedum/sistema.cncm.edu.mx"