name: Trigger Server Update

on:
  push:
    branches:
      - main

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Call Deployment Script
        run: |
          curl -s "http://sistema.cncm.edu.mx/upload_version.php?run=${{ github.run_number }}"